name: CI

on: [push, pull_request]

jobs:
  task4:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
            cd task-4
            mkdir build
            cd build
            cmake -DCMAKE_BUILD_TYPE=Release ..
            make
            cd ..
        env:
          CI: true

      - name: Test
        if: runner.os == 'Linux'
        run: |
            cd task-4
            sudo apt install picosat
            ./download.sh
            python3 ./compare.py
        env:
          CI: true
